thresholds:
  global: 10.0

  measurements:
    Val 1: 5.0
    Val 2: 5.0
    Val 3: 15.0
    Val A: 1.0
    Val B: 5.0
    Val C: 1.0
    Val X: 5.0
    Val Y: 25.0
    Val Z: 12.0
    Val I1: 20.0
    Val I2: 10.0
    Val I3: 5.0

  statistics:
    Val 1: 5.0
    Val 2: 5.0
    Val 3: 10.0
    Val A: 2.0
    Val B: 5.0
    Val C: 2.0
    Val X: 5.0
    Val Y: 10.0
    Val Z: 10.0
    Val I1: 10.0
    Val I2: 10.0
    Val I3: 10.0

files:
  ground_truth: "data/Data.csv"
  modified_data: "data/Data_modified"
  output_report: "output/comparison_report.xlsx"

csv_settings:
  delimiter: ";"
  decimal: ","
  missing_value: "NaN"